# Пропишем версию
version: '3'
# Перечислим сервисы
services:
    nginx:
         image: nginx:latest
         ports:
          - 80:80
         volumes:
          - ./logs:/etc/logs/nginx
          - ./www/mysite:/var/www
          - ./conf/nginx:/etc/nginx/conf.d
         links:
          - fpm
    fpm:
         build: ./docker/fpm
         volumes:
          - ./www/mysite:/var/www
          - ./logs:/etc/logs/php
